[workspace]
resolver = "2"
members = [ "crates/pulse", "crates/pulsevm", "crates/pulsevm_benchmark", "crates/pulsevm_database", "crates/pulsevm_core", "crates/pulsevm_crypto",
    "crates/pulsevm_grpc"
, "crates/pulsevm_name", "crates/pulsevm_proc_macros", "crates/pulsevm_serialization", "crates/pulsevm_unittests", "crates/pulsevm_e2e_boot", "crates/pulsevm_error", "crates/pulsevm_name_macro", "crates/pulsevm_billable_size", "crates/pulsevm_constants", "crates/pulsevm_keosd", "crates/pulsevm_keosd_client", "crates/pulsevm_wasm_validation", "crates/pulsevm_api_client", "crates/pulsevm_api_types", "crates/pulsevm_arena", "crates/pulsevm_arena_derive", "crates/pulsevm_contractdb", "crates/pulsevm_chaindb", "crates/pulsevm_softfloat", "crates/pulsevm_chain_types", "crates/pulsevm_abi", "crates/pulsevm_rpc", "crates/pulsevm_snapshot", "crates/pulsevm_snapshot_import"]

[profile.profiling]
inherits = "release"
debug = true
